"""QC rule plugins. Auto-discovered."""
from .base import QCRule
from .range import RangeRule
from .continuity import ContinuityRule
from .missing_sample import MissingSampleRule
from .spectral import SpectralRule
from .entropy import EntropyRule
from .cross_correlation import CrossCorrelationRule
from .psd import PSDRule
from .flatline import FlatlineRule
